---
kind: "operation"
client: "rug-cli 0.19.1"
editor:
  name: "UpgradeFrom0_7_1"
  group: "atomist-rugs"
  artifact: "rug-upgrade"
  version: "0.1.0"
  origin:
    repo: "atomist-rugs/rug-upgrade"
    branch: "master"
    sha: "e556ba9*"

---
kind: "operation"
client: "rug-cli 0.19.1"
editor:
  name: "UpgradeFrom0_7_1"
  group: "atomist-rugs"
  artifact: "rug-upgrade"
  version: "0.1.0"
  origin:
    repo: "atomist-rugs/rug-upgrade"
    branch: "master"
    sha: "e556ba9*"

---
kind: "operation"
client: "atomist 1.2"
generator:
  name: "StaticPage"
  group: "jessitron"
  artifact: "elm-rugs"
  version: "2.0.0"
  origin:
    repo: "jessitron/elm-rugs.git"
    branch: "fork/master"
    sha: "8eb0a6f"
  parameters:
    - "project_name": "ThisIsElm101"
    - "org": "satellite-of-love"
    - "version": "1.0.0"
    - "description": "helpful summary of your project, less than 80 characters"

